#!/bin/bash

# just some cool style
ansi()          { echo -e "\e[${1}m${*:2}\e[0m"; }
bold()          { ansi 1 "$@"; }
underline()     { ansi 4 "$@"; }
red()           { ansi 31 "$@"; }
green()         { ansi 92 "$@"; }
cyan()          { ansi 32 "$@"; }

filename="old"

bold "creating 127 files..."

for i in {0..126}
do
  touch "file_$i"
done

green "press [ENTER] to create an old file"
read -n 1

touch -t 1910211000 ./$filename 

cyan "'$filename' file created"
ls -al $filename

green "press [ENTER] to create new file which will delete the old file"
read -n 1

touch new

ls

green "'$filename' file deleted"

ls -al $filename

